export {
  AppProvider,
  useApp,
  useAppState,
  useAppDispatch,
  useMobileMenu,
  useActiveSection,
  usePortfolioFilter,
  useStatistics,
  useServices,
  useProcessSteps,
  useFormState,
  type AppState,
  type QuoteFormData,
  type SupportFormData,
  type PortfolioItem,
  type Statistic,
  type Service,
  type ProcessStep
} from './AppContext'
